In [1]:
import numpy as np

In [ ]:
a = np.array([2,3,4]);a

array([2, 3, 4])

In [ ]:
b = np.array([(1.5,2,3),(4,5,6)]);b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [ ]:
b.shape

(2, 3)

In [ ]:
b.ndim

2

In [ ]:
b.size

6

In [ ]:
type(b)

numpy.ndarray

In [ ]:
c = np.array([0,1,2,3])

In [ ]:
c.shape

(4,)

In [ ]:
d = np.array([[1],[2],[3],[4]])

In [ ]:
d.shape

(4, 1)

In [ ]:
d.ndim

2

In [ ]:
d.size

4

In [ ]:
fx = np.array([0,1,2,3,4],dtype='float64');fx.dtype

dtype('float64')

In [ ]:
fx

array([0., 1., 2., 3., 4.])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones((2,3,4),dtype=np.int32)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)

In [ ]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [ ]:
np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [ ]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.linspace(0,9,4,dtype=np.int32)

array([0, 3, 6, 9], dtype=int32)

In [ ]:
np.random.seed(123)
np.random.rand(3,2)

array([[0.69646919, 0.28613933],
       [0.22685145, 0.55131477],
       [0.71946897, 0.42310646]])

In [ ]:
np.random.randn(2,5)

array([[-0.09470897,  1.49138963, -0.638902  , -0.44398196, -0.43435128],
       [ 2.20593008,  2.18678609,  1.0040539 ,  0.3861864 ,  0.73736858]])

In [ ]:
np.random.randint(0,9,(2,3))

array([[6, 1, 5],
       [6, 2, 1]])

In [2]:
L = np.random.rand(100)
np.sum(L)

50.31951952637079

In [3]:
np.percentile(L, q=[30,70])

array([0.31661561, 0.65949042])

In [4]:
np.median(L)

0.5082338036233862

In [5]:
np.var(L)

0.06915157140761918

In [6]:
np.any(L>0.9)

True

In [7]:
m = np.random.rand(3,4);m

array([[0.99631685, 0.89963188, 0.33766611, 0.05286878],
       [0.50418608, 0.88309801, 0.68236476, 0.22328167],
       [0.68601312, 0.97326526, 0.48112103, 0.36137259]])

In [8]:
m.sum()

7.081186140214224

In [12]:
m.min(axis=0)

array([0.50418608, 0.88309801, 0.33766611, 0.05286878])

In [13]:
p = np.random.randn(5)
p

array([ 0.72266816,  0.35243645,  0.13876286, -0.9607413 ,  0.47516887])

In [14]:
np.sort(p)

array([-0.9607413 ,  0.13876286,  0.35243645,  0.47516887,  0.72266816])

In [15]:
np.argsort(p)

array([3, 2, 1, 4, 0], dtype=int64)

In [16]:
np.argmax(p)

0

In [18]:
np.nonzero(p)

(array([0, 1, 2, 3, 4], dtype=int64),)

In [31]:
np.where(p<0)

(array([3], dtype=int64),)

In [32]:
r = np.random.rand(4,2)
r

array([[0.83821164, 0.48841554],
       [0.20043648, 0.70073899],
       [0.089553  , 0.62892722],
       [0.52841809, 0.4625145 ]])

In [33]:
np.sort(r,axis=0)

array([[0.089553  , 0.4625145 ],
       [0.20043648, 0.48841554],
       [0.52841809, 0.62892722],
       [0.83821164, 0.70073899]])

In [34]:
np.argmin(r)

4

In [37]:
np.argmax(r,axis=1)

array([0, 1, 1, 0], dtype=int64)

In [39]:
np.where(r>0.8)

(array([0], dtype=int64), array([0], dtype=int64))

In [40]:
ints = np.array([3,3,3,2,2,1,1,4,4])
np.unique(ints)

array([1, 2, 3, 4])

In [41]:
np.in1d(ints,[4,5,6])

array([False, False, False, False, False, False, False,  True,  True])

In [42]:
values=np.array([6,0,0,3,2,5,6])
np.intersect1d(ints,values)

array([2, 3])

In [43]:
np.union1d(ints,values)

array([0, 1, 2, 3, 4, 5, 6])

In [45]:
v1 = np.array([1,2,3])
v2 = np.array([4,0,6])
v3=np.array([-7,-8,9])
M = np.vstack([v1,v2,v3])
M

array([[ 1,  2,  3],
       [ 4,  0,  6],
       [-7, -8,  9]])

In [46]:
np.diag(M)

array([1, 0, 9])

In [47]:
np.dot(M,v1)

array([14, 22,  4])

In [48]:
v1.dot(v2)

22

In [49]:
M.T

array([[ 1,  4, -7],
       [ 2,  0, -8],
       [ 3,  6,  9]])

In [50]:
np.linalg.det(M)

-203.99999999999994

In [51]:
np.linalg.eig(M)

(array([-2.12894926+0.j       ,  6.06447463+7.6840136j,
         6.06447463-7.6840136j]),
 array([[ 0.63080138+0.j        ,  0.07953839-0.31106685j,
          0.07953839+0.31106685j],
        [-0.76122227+0.j        ,  0.21856608-0.48210806j,
          0.21856608+0.48210806j],
        [-0.15043365+0.j        ,  0.78530997+0.j        ,
          0.78530997-0.j        ]]))

In [52]:
U,S,Vtranspose = np.linalg.svd(M)

In [54]:
print(U,S,Vtranspose)

[[ 0.0426978  -0.43126184  0.90121591]
 [ 0.18026878 -0.88390806 -0.43152023]
 [ 0.98269022  0.18088605  0.04000211]] [14.10472785  7.57714628  1.90879718] [[-0.43354673 -0.55131345  0.71280482]
 [-0.69064213 -0.30481292 -0.65582202]
 [-0.57883562  0.77662254  0.24860965]]


In [55]:
x=np.array([[5,0,3,3],[7,9,3,5],[2,4,7,6]])
x[x<5]

array([0, 3, 3, 3, 2, 4])

In [64]:
cols = np.any(x < -6, 0)
rows = np.any(x < 0, 1)
print(cols, rows, sep='\n')

AxisError: axis 1 is out of bounds for array of dimension 1

In [62]:
x = np.arange(-3,3)

In [58]:
x[0]

-3

In [59]:
x

array([-3, -2, -1,  0,  1,  2])

In [60]:
x[0,np.sum(x,0)>=0]

array([], dtype=int32)

In [65]:
rand = np.random.seed(1234)
x = np.random.randint(100,size=10)
x

array([47, 83, 38, 53, 76, 24, 15, 49, 23, 26])

In [66]:
ind = [3,7,4]
x[ind]

array([53, 49, 76])

In [69]:
x = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11]])
row = np.array([0,1,2])
col = np.array([2,1,3])
x[row,col]

array([ 2,  5, 11])

In [70]:
x= np.arange(-2,2.0)
x[:2]=99.0

In [71]:
x

array([99., 99.,  0.,  1.])

In [72]:
x= np.log(x-2.0)
x

C:\Users\Hyuk\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log
  """Entry point for launching an IPython kernel.


array([4.57471098, 4.57471098,        nan,        nan])

In [73]:
x[np.isnan(x)]=0
x

array([4.57471098, 4.57471098, 0.        , 0.        ])

In [ ]:
x.shp